version: '3.7'
services:
  mongodb_container:
    image: mongo:latest
    ports:
      - 27017:27017
    volumes:
      - mongodb_data_container:/data/db
  client_container:
    build: client/.
    ports:
      - 80:80
    depends_on:
      - mongodb_container
  server_container:
    build: server/.
    ports:
      - 3000:3000
    depends_on:
      - mongodb_container
    links:
      - mongodb_container

volumes:
  mongodb_data_container:
