name: Content

on:
  push:
    branches: [ content ]

jobs:
  curl:
    runs-on: ubuntu-latest
    steps:
      - name: Update mongo
        run: curl -XGET --connection-timeout 30 http://jasonlong.xyz:3000/secret/updateMongo
