name: Master

on:
  push:
    branches: [ master ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
        with:
          fetch-depth: 0

      - name: Node.js
        uses: actions/setup-node@v1
        with:
          - node-version: '8.19.2'

      - name: Dependencies
        run: npm install

      - name: Generate
        run: npm run generate

      - name: SSH
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.DEPLOY_SSH_PRIVATE }}" > ~/.ssh/id_rsa
          chmod 400 ~/.ssh/id_rsa
          ssh-keyscan -H jalong.xyz >> ~/.ssh/known_hosts
          chmod 644 ~/.ssh/known_hosts

      - name: Deploy
        run: rsync -avz dist/* root@jalong.xyz:/var/www/portal
