name: Test and Build

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  client:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Dependencies
        run: npm --prefix ./client ci
      - name: Lint
        run: npm --prefix ./client run lint
      - name: Build
        run: npm --prefix ./client run build
  server:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Node.js
        uses: actions/setup-node@v1
        with:
          node-version: '10.x'
      - name: Dependencies
        run: npm --prefix ./server ci
      - name: Lint
        run: npm --prefix ./server run lint
      - name: Build
        run: npm --prefix ./server run build
